# Generated by Django 4.1.2 on 2022-11-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeName', models.CharField(max_length=500)),
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Department', models.CharField(max_length=500)),
                ('DOJ', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('ManagerName', models.CharField(max_length=500)),
                ('ManageId', models.AutoField(primary_key=True, serialize=False)),
                ('ManagerSalary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=500)),
                ('ProjectRating', models.IntegerField()),
            ],
        ),
    ]
